### ISSUE TITLE
Scraping codes from Etherscan

### ISSUE THREAD

**Issue by shashank-srikant** [thec00n/etherscan_verified_contracts#3]
This isn't really a bug report.
Wanted to understand from you how (in)convenient it was for your team to scrape codes from Etherscan?
How long did it take, and what hurdles did you face while pulling codes from their site?

**Comment by shashank-srikant** [comment]
@b-mueller would be great to know your experience.
thanks.

**Comment by muellerberndt** [comment]
I never tried doing that :)

**Comment by shashank-srikant** [comment]
Oh. Nice.
May I ask how you've put this together then?

**Comment by muellerberndt** [comment]
It's not my repo. You should ask @thec00n 🙄

**Comment by thec00n** [comment]
@shashank-srikant I added getContracts.js. Also checkout https://github.com/thec00n/etherscan_verified_contracts/blob/master/README.md.
